### ISSUE TITLE
[Enhancement] Grab old config values from past install to use in new version

### ISSUE THREAD

**Issue by AquilaSagitta** [geerlingguy/ansible-role-php-versions#47]
Was using this to upgrade a site's php version from 7.1 to 7.3. Ran into some issues where php fpm default values weren't as expected. Had to dig through old php's install configs to get what was needed to be updated. Would be great if this installed new php versions with same config values if php already existed and the config values are relevant to new install.

**Comment by webarchitect609** [comment]
IMHO this kind of functionality is too specific for your task. And in some cases such behaviour could lead to problems. For example, if newer version introduce new options which sould be configured or deprecates usage of old option, which in turn should be removed. Therefore it should be implemented by additional tasks in your playbook.

**Comment by geerlingguy** [comment]
I agree with @webarchitect609 — you should have all your PHP configurations in your automation (and not be tweaking them on the server in an un-managed fashion), so that you can upgrade PHP versions and manage the configuration independent of the installed running PHP version on a given server.

I often have a custom `php.ini` file, and set `php_use_managed_ini: false` (using my geerlingguy.php role), and then have a task in my playbook that places my own custom php.ini in place).
