### ISSUE TITLE
Using 7.1 as php_version installs 8.2 and some 7.1

### ISSUE THREAD

**Issue by NanoPish** [geerlingguy/ansible-role-php-versions#82]
Results in both installed and 8.2 used

**Comment by NanoPish** [comment]
Probably because it is not supported, but maybe an error instead ?

**Comment by geerlingguy** [comment]
Yeah, sorry, unfortunately I can't support versions older than 7.4 anymore because a lot of the underlying packagers have dropped support as well.

If you're needing 7.1 or some other older version, I would recommend locking in the php_packages yourself (instead of relying on this role to build it correctly).
